### PR TITLE
Add repo skeleton and desktop-app framework

### PR DESCRIPTION
**Pull request by phwissmann**
Add wails.io based app with svelte frontend, a taskqueue and basic go module and package structure

### CODE REVIEW

**Comment by phwissmann** [comment]
Same changes as in https://github.com/paulscherrerinstitute/scicat-cli/pull/102 but with reviews implemented.

- [ ] Add CI pipeline

**Review by consolethinks — CHANGES_REQUESTED** [review]
Could you move the core package in internal into its own subdirectory? I think one convetion of Go is that packages are generally in folders that are named after themselves. And also, if we decide on having more than one internal package, it provides a way to clearly organize the source code. Do let me know, however, if this is not how you see it!

**Review by consolethinks — APPROVED** [review]

**Review by consolethinks — APPROVED** [review]

**Review by consolethinks — APPROVED** [review]
everything looks good

**Review by consolethinks — APPROVED** [review]
:+1:

**Pull request merged**
